### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by fega** [fega/fega.github.io#4]
- [ ] Add a better build process, aka `vue init webpack`
- [ ] Add platzi badges
- [ ] Add skill badges
- [ ] Add two very good full stack projects
- [ ] Add two very good frontend projects
- [ ] Add two very good open source contributions
- [ ] Add call to action
